# Generated by Django 5.0.6 on 2024-07-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer_Job',
            fields=[
                ('Carrer_Job_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Job_Title', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Skill', models.TextField()),
                ('Salary', models.FloatField()),
                ('Send_Resume', models.EmailField(max_length=254)),
            ],
        ),
    ]
