# Generated by Django 5.0.6 on 2024-07-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
