# Generated by Django 5.0.6 on 2024-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Subject',
            field=models.CharField(max_length=200),
        ),
    ]
