export const  USER_PROFILE_SUCCESS ="USER_PROFILE_SUCCESS"
export const  USER_PROFILE_FAILED ="USER_PROFILE_FAILED"
export const  USER_PROFILE_CREATION ="USER_PROFILE_CREATION"
export const  USER_PROFILE_LOGOUT ="USER_PROFILE_LOGOUT"

