# Generated by Django 5.0.6 on 2024-07-03 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0003_alter_product_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tax_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Shipping_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Total_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Is_Delivered', models.BooleanField(default=False)),
                ('Delivered_At', models.DateTimeField(blank=True, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('OrderItems_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Items_Data', models.JSONField(blank=True, default=dict, null=True)),
                ('Total_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Address',
            fields=[
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Shipping_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Shipping_Id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
