# Generated by Django 5.0.6 on 2024-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Products', '0003_alter_product_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
        migrations.AddField(
            model_name='order_items',
            name='product',
            field=models.ManyToManyField(to='Products.product'),
        ),
    ]
